name: autoUpload

on:
  workflow_dispatch:

jobs:
  autoUpload:
    name: Post step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PDJE_AUTO_PUSH }}
      - run: |
          git clone https://github.com/Rliop913/Project_DJ_Godot.git
          ls
          cd Project_DJ_Godot
          ls
          echo "push pull test\n" >> dummy.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dummy.txt
          git commit -m "autoPublishTest"
          git push origin main
        
  
      
