name: autoUpload

on:
  workflow_dispatch:

jobs:
  autoUpload:
    - name: set dummy
      shell: bash
      run: |
        mkdir samples
        cd samples
        touch one.txt
        touch two.txt
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: success_builds
        path: samples
    

  autoUpload:
    name: Post step
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: '*success_builds'
          merge-multiple: false
          path: builds

      - run: |
          tree .

    
      
