name: autoUpload

on:
  workflow_dispatch:

jobs:
  autoUpload:
    name: Post step
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PDJE_AUTO_PUSH }}
    steps:
      - run: |
          
          echo "Secret length: ${#GH_TOKEN}"
          gh auth status
          gh repo clone https://github.com/Rliop913/Project_DJ_Godot
          ls
          cd Project_DJ_Godot
          ls
          echo "push pull test\n" >> dummy.txt
          echo "before username"
          git config user.name "github-actions[bot]"
          echo "before useremail"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "before add"
          git add dummy.txt
          echo "before commit"
          git commit -m "autoPublishTest"
          echo "before push"
          git push origin main
        
  
      
