#include "EnumWrapper.hpp"

using namespace godot;

VARIANT_ENUM_CAST(EnumWrapper::PDJE_FX_LIST);

void
EnumWrapper::_bind_methods()
{
    BIND_ENUM_CONSTANT(COMPRESSOR);
    BIND_ENUM_CONSTANT(DISTORTION);
    BIND_ENUM_CONSTANT(ECHO);
    BIND_ENUM_CONSTANT(EQ);
    BIND_ENUM_CONSTANT(FILTER);
    BIND_ENUM_CONSTANT(FLANGER);
    BIND_ENUM_CONSTANT(OCSFILTER);
    BIND_ENUM_CONSTANT(PANNER);
    BIND_ENUM_CONSTANT(PHASER);
    BIND_ENUM_CONSTANT(ROBOT);
    BIND_ENUM_CONSTANT(ROLL);
    BIND_ENUM_CONSTANT(TRANCE);
    BIND_ENUM_CONSTANT(VOL);
}